### ISSUE TITLE
If duration flag is set, i3-timer.json should be updated with that value

### ISSUE THREAD

**Issue by NuLL3rr0r** [claudiodangelis/i3-timer#6]
For example, running:

```
/usr/local/bin/i3-timer -alarm-command="notify-send 'i3-timer' 'Alarm Elapsed!'; play /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga" -colors -duration 15
```
Outputs
```
Timer: 5m0s
```

Or
```
 /usr/local/bin/i3-timer -duration 1
```
Outputs
```
Timer: 5m0s
```

Basically, I am stuck with the 5m0s default and cannot change the duration.

**Comment by NuLL3rr0r** [comment]
The only way that I can decrease or increase the time is using scroll up/down from i3-bar then running:

```
/usr/local/bin/i3-timer -duration 2
```
Returns
```
Timer: 15m0s
```

**Comment by claudiodangelis** [comment]
Hi, good catch. `-duration` has no effect if the `~/.i3-timer.json` config file exists; if you remove that file and restart i3 you should see the correct duration.

I will fix this in a few days, thanks for reporting, and please let me know if removing the `~/.i3-timer.json` file fixes the issue.

**Comment by NuLL3rr0r** [comment]
Thank you for the quick response. Yes, I can confirm that removing `~/.i3-timer.json` and restarting i3 works.

**Comment by claudiodangelis** [comment]
Bug fixed. The duration flag will not override the current config file until user _resets_ the timer (right-click).

Thanks!
